### ISSUE TITLE
Länge der Sätze

### ISSUE THREAD

**Issue by niklaskoopmann** [Supporterino/TextAnalyzer#1]
Auszählen der Worte und  ab einem Threshold (bspw. 15 Worte) Warnung.
Bitte Semikola beachten, ich liebe die Dinger. Würde bei Punkt und Semikolon zurücksetzen.

**Comment by Herbert-Karl** [comment]
am besten kann man den Threshold selbst noch mitgeben.

**Comment by Supporterino** [comment]
Warnung is drin mit variablem Threshold, semikola werden noch nicht beachtet
